(function () {
  'use strict';

  var POWER = [
{n:1,t:"Never Outshine the Master",sub:"Make those above you feel effortlessly superior",d:"Show off too much and you inspire fear and insecurity in those above you. Make your masters appear more brilliant than they are and you reach the heights of power.",use:"Around bosses, mentors, investors, or clients. Let their guidance seem to shape your wins.",avoid:"Once you hold your own platform and answer to no master. Shrinking then only cripples you.",act:"This week, credit a senior person's input for one of your recent wins, out loud."},
{n:2,t:"Never Put Too Much Trust in Friends, Learn to Use Enemies",sub:"A reformed enemy proves more loyal than a friend",d:"Friends, used to being treated as equals, take your favors for granted and grow envious. A former enemy has more to prove and will work harder to keep your trust.",use:"When hiring or partnering. A skilled former rival can outwork a comfortable friend.",avoid:"Do not manufacture enemies for sport. This is about judgment, not paranoia.",act:"Name one person you keep close out of loyalty, not merit. Be honest about the cost."},
{n:3,t:"Conceal Your Intentions",sub:"Keep people off balance and in the dark",d:"Guide people far enough down the wrong path, wrap them in enough smoke, and they will not see your aim until it is too late to stop you.",use:"Negotiations, launches, competitive moves. Reveal the goal only once it is done.",avoid:"With true allies you rely on daily. Concealment there breeds only suspicion.",act:"Pick one goal and stop narrating it for 30 days. Let the result speak."},
{n:4,t:"Always Say Less Than Necessary",sub:"The more you say, the more ordinary you seem",d:"Say less than necessary and you appear more powerful and mysterious. Silence makes others uncomfortable, and they fill it by revealing themselves.",use:"Tense meetings and negotiations. State your point, then stop talking.",avoid:"When someone is hurting and needs to be heard. Cold silence there is cruelty.",act:"In your next negotiation, make your ask, then stay silent until they respond."},
{n:5,t:"Guard Your Reputation With Your Life",sub:"Reputation is the cornerstone of power",d:"Reputation alone can intimidate and win. Once it slips, you are exposed on every side. Build it solid and defend it before attacks arrive.",use:"Always. One flagship result is worth more than twenty forgettable ones.",avoid:"Never trade integrity to protect image. Character outranks reputation.",act:"Audit your public presence. Fix the top three things that misrepresent you."},
{n:6,t:"Court Attention at All Costs",sub:"What is unseen counts for nothing",d:"Draw attention by being larger, stranger, and more magnetic than the crowd. Never let yourself be lost in the grey mass.",use:"When launching or building a brand in a crowded market.",avoid:"When quiet execution matters more. Attention without substance invites backlash.",act:"Publish one piece this week bolder than anything you have posted before."},
{n:7,t:"Get Others to Do the Work, but Take the Credit",sub:"Use others' effort to advance your own name",d:"Use the skill, energy, and labor of others to further your cause. Their help speeds your work, and the credit makes you seem godlike.",use:"When you can delegate execution and own the vision and outcome.",avoid:"When it means robbing a junior of deserved recognition. That earns lasting resentment.",act:"Delegate one task you keep doing yourself. Own the result, not the grind."},
{n:8,t:"Make Other People Come to You",sub:"Hold the position of power, use bait if needed",d:"When you force the other person to act, you hold the leverage. Lure them onto your ground and they abandon their own plans.",use:"Sales and hiring. Build proof and let them approach you as the prize.",avoid:"When speed beats leverage. Do not confuse patience with passivity.",act:"Stop chasing one prospect. Post something that pulls them to you instead."},
{n:9,t:"Win Through Actions, Never Argument",sub:"Any victory won by words is hollow",d:"Winning an argument breeds resentment that outlasts any change of mind. Demonstrate, do not explain. Let results make your case.",use:"When someone doubts you. Answer with undeniable output.",avoid:"When a two-minute clarification prevents weeks of confusion.",act:"Pick one doubter. Do the one thing that ends the debate. Ship it."},
{n:10,t:"Avoid the Unhappy and Unlucky",sub:"Misery is contagious",d:"Emotional states spread like disease. The chronically negative pull you into their storm. Associate with the happy and fortunate instead.",use:"Choosing partners, hires, and close friends. You become your five closest people.",avoid:"Do not abandon a good person in a rough patch. This is about chronic patterns.",act:"Rate your five closest contacts on energy. Increase time with the highest."},
{n:11,t:"Learn to Keep People Dependent on You",sub:"Make yourself the one they cannot replace",d:"The more others depend on you, the freer you are. Master the one skill or relationship no one else can supply.",use:"Become irreplaceable through genuine, specialized value.",avoid:"Do not fake dependency through manipulation. Build a real moat.",act:"Name your least replaceable skill. Double down on it this quarter."},
{n:12,t:"Use Selective Honesty to Disarm",sub:"One sincere act hides a dozen calculated ones",d:"A single honest, generous gesture, especially an unexpected one, disarms suspicion and builds disproportionate trust.",use:"Opening a relationship with a client or partner. Lead with a real admission.",avoid:"When candor would needlessly wound, or hand a rival a weapon.",act:"In your next pitch, name one honest limitation up front. Watch trust rise."},
{n:13,t:"Appeal to Self-Interest, Never Mercy",sub:"Show people what they gain, not what you need",d:"When you ask for help, remind the other person of a benefit to them. They respond with enthusiasm, not reluctant obligation.",use:"Every request and proposal. Frame it around their upside.",avoid:"With people who genuinely love you. There, honesty beats strategy.",act:"Rewrite your next ask so the first line is what they get, not what you want."},
{n:14,t:"Pose as a Friend, Work as a Spy",sub:"Learn to probe without being felt",d:"Gather intelligence through friendly conversation. Ask, listen, and let people reveal what they would never volunteer.",use:"Discovery calls and research. Curiosity plus silence extracts everything.",avoid:"With people you truly trust. Do not spy on your own.",act:"Next call, ask three open questions, then go quiet. Note what surfaces."},
{n:15,t:"Crush Your Enemy Totally",sub:"A half-beaten rival returns stronger",d:"One ember left glowing will reignite. In competitive matters, finish decisively rather than stopping halfway out of mercy or fatigue.",use:"Business threats and competition. Close it fully or drop it.",avoid:"Personal relationships. This is strategy, not a way to live.",act:"Name one half-handled threat. Either end it completely or let it go."},
{n:16,t:"Use Absence to Increase Respect",sub:"Scarcity raises your value",d:"Too much presence lowers the price of your company. Once established, a well-timed withdrawal makes you more talked about and desired.",use:"After a big win or heavy output. Step back and let the work breathe.",avoid:"Before you are known. You cannot use absence you have not earned.",act:"Go quiet on one platform for a week. Watch the response when you return."},
{n:17,t:"Cultivate an Air of Unpredictability",sub:"Keep others in suspended uncertainty",d:"Predictable people hand others a sense of control. Deliberate unpredictability unsettles opponents and forces them to react to you.",use:"Against aggressive rivals who try to read and box you in.",avoid:"With your team, who need stability to trust and follow you.",act:"In one recurring interaction, break your usual pattern and observe the shift."},
{n:18,t:"Do Not Build Fortresses",sub:"Isolation is dangerous",d:"Isolation feels safe but blinds you to threats and starves you of allies. Power flows from circulation, not from walls.",use:"When you notice yourself withdrawing and dodging contact. Force yourself out.",avoid:"Do not confuse focused solitude for deep work with chronic hiding.",act:"Reach out to one person you have not spoken to in six months. No agenda."},
{n:19,t:"Know Who You Are Dealing With",sub:"Do not offend the wrong person",d:"People differ, and misjudging one can undo you. Read your target before you act, and never assume everyone reacts the same way.",use:"Before pitching, confronting, or deceiving anyone. Study them first.",avoid:"Do not let caution become endless analysis that kills action.",act:"Before your next high-stakes conversation, write what actually drives them."},
{n:20,t:"Do Not Commit to Anyone",sub:"Stay independent to stay in demand",d:"By refusing to commit fully to one side, you keep others courting you and preserve your freedom to choose. The uncommitted hold the power.",use:"When multiple parties want you. Let them compete for you.",avoid:"This is about factions and leverage, not betraying real loyalties.",act:"Define your walk-away point before your next negotiation. Write it down."},
{n:21,t:"Play a Sucker to Catch a Sucker",sub:"Seem dumber than your mark",d:"No one likes feeling stupider than others. Make your target feel smart and superior and they will drop their guard entirely.",use:"When being underestimated buys you room to move.",avoid:"When you need visible authority and respect to lead.",act:"In one setting, ask a naive question and watch what people reveal."},
{n:22,t:"Use the Surrender Tactic",sub:"Turn weakness into power",d:"When weaker, surrendering buys time and preserves you. It denies the victor the fight and leaves you free to recover and undermine them.",use:"When outmatched. Yield in form, regroup in substance.",avoid:"When holding firm actually wins. Do not surrender from fear alone.",act:"Identify one losing fight. Concede the point, keep the position."},
{n:23,t:"Concentrate Your Forces",sub:"Intensity beats scatter every time",d:"Mine one rich vein deeply rather than dabbling in many shallow ones. Concentrated force overwhelms diffused effort.",use:"Pick one niche, one offer, one channel, and go deep.",avoid:"When a vein is truly exhausted. Then pivot on evidence, not boredom.",act:"List everything you are working on. Cut it to the two that drive results."},
{n:24,t:"Play the Perfect Courtier",sub:"Master indirect, graceful influence",d:"In any power structure, the courtier thrives through subtlety, tact, and flattery that never feels like flattery. Grace is a weapon.",use:"In politically dense environments where bluntness gets you nowhere.",avoid:"Where directness and candor are the actual currency of trust.",act:"Deliver one piece of hard feedback wrapped in genuine, specific praise."},
{n:25,t:"Re-Create Yourself",sub:"Forge your own identity, do not inherit one",d:"Do not accept the role society hands you. Shape a deliberate public identity that commands attention and controls how you are seen.",use:"When rebranding yourself or your work for a new stage.",avoid:"When the persona drifts so far from you it becomes exhausting to hold.",act:"Write the identity you want in three years. Take one action toward it today."},
{n:26,t:"Keep Your Hands Clean",sub:"Let others carry the blame",d:"You must seem a model of fairness. Conceal your mistakes and mishaps behind a scapegoat or a go-between who takes the fall.",use:"When protecting a reputation that must stay spotless.",avoid:"When owning a mistake earns more trust than dodging it. Often it does.",act:"Review one mess. Decide honestly whether ownership or distance serves you."},
{n:27,t:"Play on People's Need to Believe",sub:"Create a cultlike following",d:"People yearn to believe in something. Offer a cause and a vision, keep it vague enough to fit their hopes, and they follow with fervor.",use:"Building a movement, brand, or community around a mission.",avoid:"When it curdles into manipulation of the vulnerable. Lead, do not exploit.",act:"Write the one-line belief your work stands for. Make it impossible to ignore."},
{n:28,t:"Enter Action With Boldness",sub:"Hesitation invites disaster",d:"If you are unsure, do not attempt it. Boldness makes any act seem stronger, while timidity magnifies every flaw and invites attack.",use:"At the moment of commitment. Go all in or do not go.",avoid:"Boldness is not recklessness. Plan first, then strike without hesitation.",act:"Name one move you keep half-doing. Commit to it fully this week."},
{n:29,t:"Plan All the Way to the End",sub:"The ending is everything",d:"Plan to the last step and you will not be overwhelmed by circumstance. Foresee every consequence so nothing derails you.",use:"Before starting any project or negotiation. Work backward from the ideal end.",avoid:"Do not plan so far you never begin. Analysis paralysis kills more than bad plans.",act:"Write one paragraph describing the perfect end state. That is your roadmap."},
{n:30,t:"Make Your Accomplishments Seem Effortless",sub:"Conceal the toil, reveal only the result",d:"Your actions should seem natural and easy. Hide the sweat and the tricks, and act as though you could do far more with ease.",use:"In presentations, portfolios, and delivery. Show inevitability, not struggle.",avoid:"When teaching. Then show the struggle so others know it is normal.",act:"Rewrite one case study to emphasize the elegant outcome, not the chaos."},
{n:31,t:"Control the Options",sub:"Make others choose from cards you dealt",d:"Give people choices that all lead where you want. They feel in control while you quietly determine the outcome.",use:"In negotiation and sales. Offer options that all serve your aim.",avoid:"When trust depends on genuine openness, not a rigged menu.",act:"Design your next offer as three choices, each a win for you."},
{n:32,t:"Play to People's Fantasies",sub:"Sell the dream, not the grey truth",d:"Truth is often drab. People flee it toward anyone who conjures romance and possibility. Feed the fantasy and a following forms.",use:"In marketing and vision-casting. Speak to the dream behind the need.",avoid:"When honesty is what actually earns the sale and the loyalty.",act:"Reframe one offer around the transformation, not the features."},
{n:33,t:"Discover Each Person's Thumbscrew",sub:"Everyone has a weakness",d:"There is always a soft spot, an insecurity, a need. Find it and you hold a lever over the person.",use:"In persuasion and negotiation. Understand what they truly want or fear.",avoid:"Weaponizing this against people you should protect corrodes everything.",act:"For one key relationship, identify the real need driving their behavior."},
{n:34,t:"Be Royal in Your Own Fashion",sub:"Act like a king to be treated as one",d:"The way you carry yourself sets how others value you. Project confidence and high standards and the world adjusts to meet them.",use:"When entering rooms and markets that judge by presence.",avoid:"When arrogance replaces substance. Bearing must be backed by delivery.",act:"Raise your price or standard on one thing to match your real worth."},
{n:35,t:"Master the Art of Timing",sub:"Know when to wait and when to strike",d:"Never seem to rush. Sense the spirit of the times, hold back when needed, and strike hard the instant the moment ripens.",use:"On decisions you are rushing from anxiety rather than urgency.",avoid:"When hesitation is just fear dressed up as patience.",act:"Take one anxious decision and give it 72 hours. Then act if it still holds."},
{n:36,t:"Disdain Things You Cannot Have",sub:"Ignoring is the best revenge",d:"Acknowledging a petty problem gives it life and hands your rival attention. Often the most powerful response is to turn away.",use:"Against trolls, minor rivals, and losses not worth the fight.",avoid:"When ignoring a real threat lets it grow. Judge the stakes honestly.",act:"Pick one thing draining your attention. Withdraw from it completely."},
{n:37,t:"Create Compelling Spectacles",sub:"Striking imagery commands attention",d:"Grand visuals and symbolic gestures gather crowds and radiate presence and power without a word of argument.",use:"Launches, brand moments, and pitches. Show, do not just tell.",avoid:"When spectacle papers over an empty product. Build substance first.",act:"Design one visually striking moment for your next launch."},
{n:38,t:"Think as You Like, Behave Like Others",sub:"Flaunting difference makes you a target",d:"Keep radical ideas to yourself and blend in outwardly. Save the unconventional for those with the power to withstand backlash.",use:"In traditional environments where you must first pass the gatekeepers.",avoid:"When conformity would betray a core value worth defending.",act:"Keep one contrarian view private for two weeks while you act on it quietly."},
{n:39,t:"Stir Up Waters to Catch Fish",sub:"Stay calm; make others lose their heads",d:"Anger and emotion are strategically useless for you but priceless in an opponent. Provoke them into reacting while you stay cool.",use:"Against a rival whose composure is their strength.",avoid:"When the disturbance splashes back and damages your own footing.",act:"In one tense moment, hold total calm and watch who cracks first."},
{n:40,t:"Despise the Free Lunch",sub:"What is free carries a hidden price",d:"What has worth is worth paying for. Free things come laced with obligation or inferior quality. Pay your way and stay unentangled.",use:"When a free offer would quietly cost you leverage or independence.",avoid:"Genuine generosity exists. Do not turn frugality into paranoia.",act:"Examine one free arrangement. Name the hidden cost you are paying."},
{n:41,t:"Avoid Stepping Into a Great Person's Shoes",sub:"Escape the shadow of a predecessor",d:"What comes first always seems greater. Following a famous predecessor, you must not coast on their name. Clear your own space and identity.",use:"When you inherit a role, brand, or legacy built by someone larger.",avoid:"Do not discard everything that worked just to prove you are different.",act:"Name one thing that will be unmistakably yours, not your predecessor's."},
{n:42,t:"Strike the Shepherd",sub:"Scatter the sheep by removing the leader",d:"Trouble usually traces to a single strong individual. Neutralize that source and the followers lose their center.",use:"When a group's resistance flows from one instigator.",avoid:"When you misidentify the source and punish the wrong person.",act:"In one stuck conflict, find the true source of resistance before acting."},
{n:43,t:"Work on the Hearts and Minds of Others",sub:"Coerce and they resist; seduce and they follow",d:"Force breeds a reaction that eventually works against you. Win people's affection and belief and they carry your cause willingly.",use:"In leadership and long-term influence. Move the heart, then the hand.",avoid:"When flattery replaces the substance people can see through.",act:"For one person you need, learn what they value, then speak to it."},
{n:44,t:"Disarm With the Mirror Effect",sub:"Reflect people to unsettle and seduce",d:"Mirroring what others do or feel humiliates rivals and mesmerizes targets, teaching you their moves while masking your own intentions.",use:"When studying an opponent or building fast rapport.",avoid:"When it reads as mockery and hardens the very person you court.",act:"In one negotiation, mirror their pace and tone before making your move."},
{n:45,t:"Preach Change, but Reform Slowly",sub:"Too much change too fast breeds revolt",d:"People crave the idea of change but fear too much of it at once. Speak the language of reform while adjusting reality gradually.",use:"When leading a team or user base through a transition.",avoid:"When boldness is exactly what a stagnant situation demands.",act:"Roll out one big change as a sequence of smaller, digestible steps."},
{n:46,t:"Never Appear Too Perfect",sub:"Envy is a silent, dangerous enemy",d:"Appearing flawless breeds envy that works against you in the dark. Admit a harmless flaw to seem human and defuse resentment.",use:"When your success is drawing quiet hostility.",avoid:"Do not fake weakness so clumsily it reads as false modesty.",act:"In one setting, own a small genuine shortcoming out loud."},
{n:47,t:"Learn When to Stop",sub:"In victory, do not overreach",d:"The moment of victory is the moment of greatest danger. Set your goal, and when you reach it, stop. Momentum tempts you into ruin.",use:"After a win, when the urge to push further takes over.",avoid:"Do not confuse disciplined stopping with quitting on real momentum.",act:"Define the finish line for your current push, and honor it when you hit it."},
{n:48,t:"Assume Formlessness",sub:"Be fluid; adapt faster than they can pin you",d:"Fixed form makes you a target. Stay fluid, adaptable, and in motion, and no attack can find a shape to strike.",use:"In fast-changing markets where rigidity gets punished.",avoid:"Formlessness is not aimlessness. Adapt around a stable core purpose.",act:"Name one rigid process. Rebuild it to flex with changing conditions."}
  ];

  var UNIVERSAL = [
{n:1,t:"The Law of Divine Oneness",sub:"Everything is connected",d:"Everything and everyone is interconnected. What you think, say, and do ripples outward and touches the whole.",use:"Treat every action as if it touches the larger web, because it does.",avoid:"Do not use oneness to erase responsibility for your specific choices.",act:"Do one small thing today as if the whole world could feel it."},
{n:2,t:"The Law of Vibration",sub:"Everything is in constant motion",d:"Everything vibrates at its own frequency, down to your thoughts and emotions. Nothing truly rests.",use:"Raise your state deliberately; your frequency shapes what you attract and notice.",avoid:"This is about your inner state, not a substitute for real action.",act:"Notice your energy right now. Shift it up one notch on purpose."},
{n:3,t:"The Law of Correspondence",sub:"As above, so below",d:"Your outer life mirrors your inner world. External reality reflects your dominant inner patterns.",use:"When life feels chaotic, look inward for the pattern first.",avoid:"Do not use it to blame yourself for everything outside your control.",act:"Pick one outer frustration. Ask what inner pattern it mirrors."},
{n:4,t:"The Law of Attraction",sub:"Like attracts like",d:"You draw toward you what matches your dominant thoughts, feelings, and energy, positive or negative.",use:"Hold a clear, felt image of what you want and act from it.",avoid:"Wishing without action is fantasy. Attraction pairs with effort.",act:"Write what you want in the present tense. Read it, feel it, then act."},
{n:5,t:"The Law of Inspired Action",sub:"Thought must become movement",d:"Attraction only completes through action. You must take concrete steps toward what you seek, not merely visualize it.",use:"Turn every intention into one physical, do-it-now step.",avoid:"Do not wait for perfect inspiration. Motion creates it.",act:"Take one imperfect action toward a goal in the next hour."},
{n:6,t:"The Law of Perpetual Transmutation of Energy",sub:"Energy always changes form",d:"Energy is always in motion and can be transformed. Higher energy transmutes lower, so your focus reshapes your reality.",use:"Redirect anger, fear, or restlessness into work and creation.",avoid:"Suppression is not transmutation. Channel the energy, do not bury it.",act:"Take one difficult emotion today and pour it into productive work."},
{n:7,t:"The Law of Cause and Effect",sub:"Every action returns",d:"Nothing happens by chance. Every action sets consequences in motion that eventually return to you.",use:"Choose actions by the harvest you want to reap later.",avoid:"Do not expect instant returns. Causes ripen on their own schedule.",act:"Plant one deliberate good cause today with no expectation of quick reward."},
{n:8,t:"The Law of Compensation",sub:"You reap what you sow",d:"You are compensated in kind for what you give: your effort, contribution, and generosity return as abundance.",use:"Give real value first; the compensation follows the contribution.",avoid:"Giving to manipulate a return poisons the exchange.",act:"Overdeliver on one thing this week without asking for anything back."},
{n:9,t:"The Law of Relativity",sub:"Nothing is good or bad until compared",d:"Everything is neutral until you compare it. Your challenges carry only the weight and meaning you assign them.",use:"Reframe a hardship by comparing it to something far worse.",avoid:"Do not use comparison to minimize a real problem into denial.",act:"Take one current struggle and place it beside a harder one. Feel the shift."},
{n:10,t:"The Law of Polarity",sub:"Everything has an opposite",d:"All things have two poles. Cold is degrees of hot; despair holds the seed of hope. Opposites are the same thing in degree.",use:"In any low, deliberately locate the opposite pole and move toward it.",avoid:"Do not deny the painful pole. Acknowledge it, then choose the other.",act:"Name one bad situation, then name its hidden opposite. Aim for it."},
{n:11,t:"The Law of Rhythm",sub:"Everything moves in cycles",d:"Everything flows in tides and rhythms: seasons, moods, momentum. Down cycles are natural and always turn.",use:"Ride high tides hard; rest and prepare during the low ones.",avoid:"Do not mistake a down cycle for a permanent state. It passes.",act:"Identify which cycle you are in now. Match your effort to it."},
{n:12,t:"The Law of Gender",sub:"Creation needs both energies",d:"Everything holds masculine and feminine energies: action and receptivity, output and rest. Both are needed to create.",use:"Balance bold action with patience and gestation in your work.",avoid:"Do not force all-action all the time. Ideas need incubation too.",act:"Pair one bold push this week with real, guilt-free rest."}
  ];

  function applyPower() {
    if (typeof LAWS === 'undefined') return;
    LAWS.length = 0;
    for (var i = 0; i < POWER.length; i++) LAWS.push(POWER[i]);
    if (typeof renderLaws === 'function') renderLaws();
    var sub = document.querySelector('#sec-laws .section-sub');
    if (sub) sub.textContent = 'All 48 laws: when to use, when to avoid';
  }

  function lawCard(l, useLabel, avoidLabel) {
    return '<div class="lc"><div class="lc-num">' + l.n + '</div><div><div class="lc-title">' + l.t + '</div><div class="lc-sub">' + l.sub + '</div><div class="lc-desc">' + l.d + '</div><div class="lc-when"><div class="lc-box use"><div class="lc-box-label">' + useLabel + '</div>' + l.use + '</div><div class="lc-box avoid"><div class="lc-box-label">' + avoidLabel + '</div>' + l.avoid + '</div></div><div class="lc-action"><div class="lc-action-label">Action Step</div>' + l.act + '</div></div></div>';
  }

  function renderUniversal() {
    var box = document.getElementById('universal-box');
    if (!box) return;
    box.innerHTML = UNIVERSAL.map(function (l) { return lawCard(l, 'In Practice', 'Common Misread'); }).join('');
  }

  function showUniversal() {
    document.getElementById('hero').style.display = 'none';
    var sections = document.querySelectorAll('.section');
    for (var i = 0; i < sections.length; i++) sections[i].classList.remove('active');
    document.getElementById('sec-universal').classList.add('active');
    if (typeof setNav === 'function') setNav('universal');
    renderUniversal();
    window.scrollTo({ top: 0 });
  }

  function injectUniversal() {
    if (document.getElementById('sec-universal')) return;
    var section = document.createElement('div');
    section.className = 'section';
    section.id = 'sec-universal';
    section.innerHTML = '<div class="section-top"><button class="back-btn" id="back-universal">\u2190 Back</button><div class="section-title">Universal Laws</div><div class="section-sub">Timeless laws of life and reality</div></div><div id="universal-box"></div>';
    document.getElementById('bottom-nav').insertAdjacentElement('beforebegin', section);

    var nav = document.createElement('button');
    nav.className = 'bnav-btn';
    nav.setAttribute('data-nav', 'universal');
    nav.innerHTML = '<span class="bnav-icon">\u2726</span>Universe';
    var settings = document.querySelector('[data-nav="settings"]');
    settings.parentNode.insertBefore(nav, settings);
    nav.addEventListener('click', showUniversal);
    document.getElementById('back-universal').addEventListener('click', showHero);
    renderUniversal();
  }

  function setup() {
    applyPower();
    injectUniversal();
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', setup);
  else setup();
})();
