(function () {
  'use strict';

  var POWER = [
{n:1,t:"Never Outshine the Master",sub:"Make those above you feel effortlessly superior",d:"Show off too much and you inspire fear and insecurity in those above you. Make your masters appear more brilliant than they are and you reach the heights of power.",use:"Around bosses, mentors, investors, or clients. Let their guidance seem to shape your wins.",avoid:"Once you hold your own platform and answer to no master. Shrinking then only cripples you.",act:"This week, credit a senior person's input for one of your recent wins, out loud."},
{n:2,t:"Never Put Too Much Trust in Friends, Learn to Use Enemies",sub:"A reformed enemy proves more loyal than a friend",d:"Friends, used to being treated as equals, take your favors for granted and grow envious. A former enemy has more to prove and will work harder to keep your trust.",use:"When hiring or partnering. A skilled former rival can outwork a comfortable friend.",avoid:"Do not manufacture enemies for sport. This is about judgment, not paranoia.",act:"Name one person you keep close out of loyalty, not merit. Be honest about the cost."},
{n:3,t:"Conceal Your Intentions",sub:"Keep people off balance and in the dark",d:"Guide people far enough down the wrong path, wrap them in enough smoke, and they will not see your aim until it is too late to stop you.",use:"Negotiations, launches, competitive moves. Reveal the goal only once it is done.",avoid:"With true allies you rely on daily. Concealment there breeds only suspicion.",act:"Pick one goal and stop narrating it for 30 days. Let the result speak."},
{n:4,t:"Always Say Less Than Necessary",sub:"The more you say, the more ordinary you seem",d:"Say less than necessary and you appear more powerful and mysterious. Silence makes others uncomfortable, and they fill it by revealing themselves.",use:"Tense meetings and negotiations. State your point, then stop talking.",avoid:"When someone is hurting and needs to be heard. Cold silence there is cruelty.",act:"In your next negotiation, make your ask, then stay silent until they respond."},
{n:5,t:"Guard Your Reputation With Your Life",sub:"Reputation is the cornerstone of power",d:"Reputation alone can intimidate and win. Once it slips, you are exposed on every side. Build it solid and defend it before attacks arrive.",use:"Always. One flagship result is worth more than twenty forgettable ones.",avoid:"Never trade integrity to protect image. Character outranks reputation.",act:"Audit your public presence. Fix the top three things that misrepresent you."},
{n:6,t:"Court Attention at All Costs",sub:"What is unseen counts for nothing",d:"Draw attention by being larger, stranger, and more magnetic than the crowd. Never let yourself be lost in the grey mass.",use:"When launching or building a brand in a crowded market.",avoid:"When quiet execution matters more. Attention without substance invites backlash.",act:"Publish one piece this week bolder than anything you have posted before."},
{n:7,t:"Get Others to Do the Work, but Take the Credit",sub:"Use others' effort to advance your own name",d:"Use the skill, energy, and labor of others to further your cause. Their help speeds your work, and the credit makes you seem godlike.",use:"When you can delegate execution and own the vision and outcome.",avoid:"When it means robbing a junior of deserved recognition. That earns lasting resentment.",act:"Delegate one task you keep doing yourself. Own the result, not the grind."},
{n:8,t:"Make Other People Come to You",sub:"Hold the position of power, use bait if needed",d:"When you force the other person to act, you hold the leverage. Lure them onto your ground and they abandon their own plans.",use:"Sales and hiring. Build proof and let them approach you as the prize.",avoid:"When speed beats leverage. Do not confuse patience with passivity.",act:"Stop chasing one prospect. Post something that pulls them to you instead."},
{n:9,t:"Win Through Actions, Never Argument",sub:"Any victory won by words is hollow",d:"Winning an argument breeds resentment that outlasts any change of mind. Demonstrate, do not explain. Let results make your case.",use:"When someone doubts you. Answer with undeniable output.",avoid:"When a two-minute clarification prevents weeks of confusion.",act:"Pick one doubter. Do the one thing that ends the debate. Ship it."},
{n:10,t:"Avoid the Unhappy and Unlucky",sub:"Misery is contagious",d:"Emotional states spread like disease. The chronically negative pull you into their storm. Associate with the happy and fortunate instead.",use:"Choosing partners, hires, and close friends. You become your five closest people.",avoid:"Do not abandon a good person in a rough patch. This is about chronic patterns.",act:"Rate your five closest contacts on energy. Increase time with the highest."},
{n:11,t:"Learn to Keep People Dependent on You",sub:"Make yourself the one they cannot replace",d:"The more others depend on you, the freer you are. Master the one skill or relationship no one else can supply.",use:"Become irreplaceable through genuine, specialized value.",avoid:"Do not fake dependency through manipulation. Build a real moat.",act:"Name your least replaceable skill. Double down on it this quarter."},
{n:12,t:"Use Selective Honesty to Disarm",sub:"One sincere act hides a dozen calculated ones",d:"A single honest, generous gesture, especially an unexpected one, disarms suspicion and builds disproportionate trust.",use:"Opening a relationship with a client or partner. Lead with a real admission.",avoid:"When candor would needlessly wound, or hand a rival a weapon.",act:"In your next pitch, name one honest limitation up front. Watch trust rise."},
{n:13,t:"Appeal to Self-Interest, Never Mercy",sub:"Show people what they gain, not what you need",d:"When you ask for help, remind the other person of a benefit to them. They respond with enthusiasm, not reluctant obligation.",use:"Every request and proposal. Frame it around their upside.",avoid:"With people who genuinely love you. There, honesty beats strategy.",act:"Rewrite your next ask so the first line is what they get, not what you want."},
{n:14,t:"Pose as a Friend, Work as a Spy",sub:"Learn to probe without being felt",d:"Gather intelligence through friendly conversation. Ask, listen, and let people reveal what they would never volunteer.",use:"Discovery calls and research. Curiosity plus silence extracts everything.",avoid:"With people you truly trust. Do not spy on your own.",act:"Next call, ask three open questions, then go quiet. Note what surfaces."},
{n:15,t:"Crush Your Enemy Totally",sub:"A half-beaten rival returns stronger",d:"One ember left glowing will reignite. In competitive matters, finish decisively rather than stopping halfway out of mercy or fatigue.",use:"Business threats and competition. Close it fully or drop it.",avoid:"Personal relationships. This is strategy, not a way to live.",act:"Name one half-handled threat. Either end it completely or let it go."},
{n:16,t:"Use Absence to Increase Respect",sub:"Scarcity raises your value",d:"Too much presence lowers the price of your company. Once established, a well-timed withdrawal makes you more talked about and desired.",use:"After a big win or heavy output. Step back and let the work breathe.",avoid:"Before you are known. You cannot use absence you have not earned.",act:"Go quiet on one platform for a week. Watch the response when you return."},
{n:17,t:"Cultivate an Air of Unpredictability",sub:"Keep others in suspended uncertainty",d:"Predictable people hand others a sense of control. Deliberate unpredictability unsettles opponents and forces them to react to you.",use:"Against aggressive rivals who try to read and box you in.",avoid:"With your team, who need stability to trust and follow you.",act:"In one recurring interaction, break your usual pattern and observe the shift."},
{n:18,t:"Do Not Build Fortresses",sub:"Isolation is dangerous",d:"Isolation feels safe but blinds you to threats and starves you of allies. Power flows from circulation, not from walls.",use:"When you notice yourself withdrawing and dodging contact. Force yourself out.",avoid:"Do not confuse focused solitude for deep work with chronic hiding.",act:"Reach out to one person you have not spoken to in six months. No agenda."},
{n:19,t:"Know Who You Are Dealing With",sub:"Do not offend the wrong person",d:"People differ, and misjudging one can undo you. Read your target before you act, and never assume everyone reacts the same way.",use:"Before pitching, confronting, or deceiving anyone. Study them first.",avoid:"Do not let caution become endless analysis that kills action.",act:"Before your next high-stakes conversation, write what actually drives them."},
{n:20,t:"Do Not Commit to Anyone",sub:"Stay independent to stay in demand",d:"By refusing to commit fully to one side, you keep others courting you and preserve your freedom to choose. The uncommitted hold the power.",use:"When multiple parties want you. Let them compete for you.",avoid:"This is about factions and leverage, not betraying real loyalties.",act:"Define your walk-away point before your next negotiation. Write it down."},
{n:21,t:"Play a Sucker to Catch a Sucker",sub:"Seem dumber than your mark",d:"No one likes feeling stupider than others. Make your target feel smart and superior and they will drop their guard entirely.",use:"When being underestimated buys you room to move.",avoid:"When you need visible authority and respect to lead.",act:"In one setting, ask a naive question and watch what people reveal."},
{n:22,t:"Use the Surrender Tactic",sub:"Turn weakness into power",d:"When weaker, surrendering buys time and preserves you. It denies the victor the fight and leaves you free to recover and undermine them.",use:"When outmatched. Yield in form, regroup in substance.",avoid:"When holding firm actually wins. Do not surrender from fear alone.",act:"Identify one losing fight. Concede the point, keep the position."},
{n:23,t:"Concentrate Your Forces",sub:"Intensity beats scatter every time",d:"Mine one rich vein deeply rather than dabbling in many shallow ones. Concentrated force overwhelms diffused effort.",use:"Pick one niche, one offer, one channel, and go deep.",avoid:"When a vein is truly exhausted. Then pivot on evidence, not boredom.",act:"List everything you are working on. Cut it to the two that drive results."},
{n:24,t:"Play the Perfect Courtier",sub:"Master indirect, graceful influence",d:"In any power structure, the courtier thrives through subtlety, tact, and flattery that never feels like flattery. Grace is a weapon.",use:"In politically dense environments where bluntness gets you nowhere.",avoid:"Where directness and candor are the actual currency of trust.",act:"Deliver one piece of hard feedback wrapped in genuine, specific praise."},
{n:25,t:"Re-Create Yourself",sub:"Forge your own identity, do not inherit one",d:"Do not accept the role society hands you. Shape a deliberate public identity that commands attention and controls how you are seen.",use:"When rebranding yourself or your work for a new stage.",avoid:"When the persona drifts so far from you it becomes exhausting to hold.",act:"Write the identity you want in three years. Take one action toward it today."},
{n:26,t:"Keep Your Hands Clean",sub:"Let others carry the blame",d:"You must seem a model of fairness. Conceal your mistakes and mishaps behind a scapegoat or a go-between who takes the fall.",use:"When protecting a reputation that must stay spotless.",avoid:"When owning a mistake earns more trust than dodging it. Often it does.",act:"Review one mess. Decide honestly whether ownership or distance serves you."},
{n:27,t:"Play on People's Need to Believe",sub:"Create a cultlike following",d:"People yearn to believe in something. Offer a cause and a vision, keep it vague enough to fit their hopes, and they follow with fervor.",use:"Building a movement, brand, or community around a mission.",avoid:"When it curdles into manipulation of the vulnerable. Lead, do not exploit.",act:"Write the one-line belief your work stands for. Make it impossible to ignore."},
{n:28,t:"Enter Action With Boldness",sub:"Hesitation invites disaster",d:"If you are unsure, do not attempt it. Boldness makes any act seem stronger, while timidity magnifies every flaw and invites attack.",use:"At the moment of commitment. Go all in or do not go.",avoid:"Boldness is not recklessness. Plan first, then strike without hesitation.",act:"Name one move you keep half-doing. Commit to it fully this week."},
{n:29,t:"Plan All the Way to the End",sub:"The ending is everything",d:"Plan to the last step and you will not be overwhelmed by circumstance. Foresee every consequence so nothing derails you.",use:"Before starting any project or negotiation. Work backward from the ideal end.",avoid:"Do not plan so far you never begin. Analysis paralysis kills more than bad plans.",act:"Write one paragraph describing the perfect end state. That is your roadmap."},
{n:30,t:"Make Your Accomplishments Seem Effortless",sub:"Conceal the toil, reveal only the result",d:"Your actions should seem natural and easy. Hide the sweat and the tricks, and act as though you could do far more with ease.",use:"In presentations, portfolios, and delivery. Show inevitability, not struggle.",avoid:"When teaching. Then show the struggle so others know it is normal.",act:"Rewrite one case study to emphasize the elegant outcome, not the chaos."},
{n:31,t:"Control the Options",sub:"Make others choose from cards you dealt",d:"Give people choices that all lead where you want. They feel in control while you quietly determine the outcome.",use:"In negotiation and sales. Offer options that all serve your aim.",avoid:"When trust depends on genuine openness, not a rigged menu.",act:"Design your next offer as three choices, each a win for you."},
{n:32,t:"Play to People's Fantasies",sub:"Sell the dream, not the grey truth",d:"Truth is often drab. People flee it toward anyone who conjures romance and possibility. Feed the fantasy and a following forms.",use:"In marketing and vision-casting. Speak to the dream behind the need.",avoid:"When honesty is what actually earns the sale and the loyalty.",act:"Reframe one offer around the transformation, not the features."},
{n:33,t:"Discover Each Person's Thumbscrew",sub:"Everyone has a weakness",d:"There is always a soft spot, an insecurity, a need. Find it and you hold a lever over the person.",use:"In persuasion and negotiation. Understand what they truly want or fear.",avoid:"Weaponizing this against people you should protect corrodes everything.",act:"For one key relationship, identify the real need driving their behavior."},
{n:34,t:"Be Royal in Your Own Fashion",sub:"Act like a king to be treated as one",d:"The way you carry yourself sets how others value you. Project confidence and high standards and the world adjusts to meet them.",use:"When entering rooms and markets that judge by presence.",avoid:"When arrogance replaces substance. Bearing must be backed by delivery.",act:"Raise your price or standard on one thing to match your real worth."},
{n:35,t:"Master the Art of Timing",sub:"Know when to wait and when to strike",d:"Never seem to rush. Sense the spirit of the times, hold back when needed, and strike hard the instant the moment ripens.",use:"On decisions you are rushing from anxiety rather than urgency.",avoid:"When hesitation is just fear dressed up as patience.",act:"Take one anxious decision and give it 72 hours. Then act if it still holds."},
{n:36,t:"Disdain Things You Cannot Have",sub:"Ignoring is the best revenge",d:"Acknowledging a petty problem gives it life and hands your rival attention. Often the most powerful response is to turn away.",use:"Against trolls, minor rivals, and losses not worth the fight.",avoid:"When ignoring a real threat lets it grow. Judge the stakes honestly.",act:"Pick one thing draining your attention. Withdraw from it completely."},
{n:37,t:"Create Compelling Spectacles",sub:"Striking imagery commands attention",d:"Grand visuals and symbolic gestures gather crowds and radiate presence and power without a word of argument.",use:"Launches, brand moments, and pitches. Show, do not just tell.",avoid:"When spectacle papers over an empty product. Build substance first.",act:"Design one visually striking moment for your next launch."},
{n:38,t:"Think as You Like, Behave Like Others",sub:"Flaunting difference makes you a target",d:"Keep radical ideas to yourself and blend in outwardly. Save the unconventional for those with the power to withstand backlash.",use:"In traditional environments where you must first pass the gatekeepers.",avoid:"When conformity would betray a core value worth defending.",act:"Keep one contrarian view private for two weeks while you act on it quietly."},
{n:39,t:"Stir Up Waters to Catch Fish",sub:"Stay calm; make others lose their heads",d:"Anger and emotion are strategically useless for you but priceless in an opponent. Provoke them into reacting while you stay cool.",use:"Against a rival whose composure is their strength.",avoid:"When the disturbance splashes back and damages your own footing.",act:"In one tense moment, hold total calm and watch who cracks first."},
{n:40,t:"Despise the Free Lunch",sub:"What is free carries a hidden price",d:"What has worth is worth paying for. Free things come laced with obligation or inferior quality. Pay your way and stay unentangled.",use:"When a free offer would quietly cost you leverage or independence.",avoid:"Genuine generosity exists. Do not turn frugality into paranoia.",act:"Examine one free arrangement. Name the hidden cost you are paying."},
{n:41,t:"Avoid Stepping Into a Great Person's Shoes",sub:"Escape the shadow of a predecessor",d:"What comes first always seems greater. Following a famous predecessor, you must not coast on their name. Clear your own space and identity.",use:"When you inherit a role, brand, or legacy built by someone larger.",avoid:"Do not discard everything that worked just to prove you are different.",act:"Name one thing that will be unmistakably yours, not your predecessor's."},
{n:42,t:"Strike the Shepherd",sub:"Scatter the sheep by removing the leader",d:"Trouble usually traces to a single strong individual. Neutralize that source and the followers lose their center.",use:"When a group's resistance flows from one instigator.",avoid:"When you misidentify the source and punish the wrong person.",act:"In one stuck conflict, find the true source of resistance before acting."},
{n:43,t:"Work on the Hearts and Minds of Others",sub:"Coerce and they resist; seduce and they follow",d:"Force breeds a reaction that eventually works against you. Win people's affection and belief and they carry your cause willingly.",use:"In leadership and long-term influence. Move the heart, then the hand.",avoid:"When flattery replaces the substance people can see through.",act:"For one person you need, learn what they value, then speak to it."},
{n:44,t:"Disarm With the Mirror Effect",sub:"Reflect people to unsettle and seduce",d:"Mirroring what others do or feel humiliates rivals and mesmerizes targets, teaching you their moves while masking your own intentions.",use:"When studying an opponent or building fast rapport.",avoid:"When it reads as mockery and hardens the very person you court.",act:"In one negotiation, mirror their pace and tone before making your move."},
{n:45,t:"Preach Change, but Reform Slowly",sub:"Too much change too fast breeds revolt",d:"People crave the idea of change but fear too much of it at once. Speak the language of reform while adjusting reality gradually.",use:"When leading a team or user base through a transition.",avoid:"When boldness is exactly what a stagnant situation demands.",act:"Roll out one big change as a sequence of smaller, digestible steps."},
{n:46,t:"Never Appear Too Perfect",sub:"Envy is a silent, dangerous enemy",d:"Appearing flawless breeds envy that works against you in the dark. Admit a harmless flaw to seem human and defuse resentment.",use:"When your success is drawing quiet hostility.",avoid:"Do not fake weakness so clumsily it reads as false modesty.",act:"In one setting, own a small genuine shortcoming out loud."},
{n:47,t:"Learn When to Stop",sub:"In victory, do not overreach",d:"The moment of victory is the moment of greatest danger. Set your goal, and when you reach it, stop. Momentum tempts you into ruin.",use:"After a win, when the urge to push further takes over.",avoid:"Do not confuse disciplined stopping with quitting on real momentum.",act:"Define the finish line for your current push, and honor it when you hit it."},
{n:48,t:"Assume Formlessness",sub:"Be fluid; adapt faster than they can pin you",d:"Fixed form makes you a target. Stay fluid, adaptable, and in motion, and no attack can find a shape to strike.",use:"In fast-changing markets where rigidity gets punished.",avoid:"Formlessness is not aimlessness. Adapt around a stable core purpose.",act:"Name one rigid process. Rebuild it to flex with changing conditions."}
  ];

  var LIFE = [
{n:1,t:"The Pareto Principle",sub:"80% of results come from 20% of effort",d:"Roughly 80 percent of outcomes flow from about 20 percent of causes. A small set of tasks, clients, and habits quietly drives the vast majority of your results.",use:"Audit your work for the vital few tasks and relationships that create most of the value, then pour your energy there.",avoid:"The ratio is a rough guide, not a hard law. Do not use it to neglect essential but unglamorous work.",act:"List this week's tasks. Circle the two that create most of the value. Do those first."},
{n:2,t:"Parkinson's Law",sub:"Work expands to fill the time you give it",d:"A task swells to consume whatever time you allow. Give yourself a week and it takes a week; give yourself an afternoon and it is somehow done by evening.",use:"Set tight, slightly uncomfortable deadlines to force focus and kill perfectionism.",avoid:"Do not cut time so hard that quality collapses or you burn out chasing artificial urgency.",act:"Take one task and halve the time you planned for it. Start now."},
{n:3,t:"Eat the Frog",sub:"Do your hardest task first",d:"If the first thing you do each morning is your most important and most dreaded task, your 'frog', the rest of the day feels light and momentum carries you.",use:"Each morning, name the one task you are most tempted to avoid and do it before anything else.",avoid:"Do not let it become an excuse to schedule the impossible before you are even awake.",act:"Name tomorrow's frog tonight. Do it first thing, before email."},
{n:4,t:"The Two-Minute Rule",sub:"If it takes under two minutes, do it now",d:"Any task that takes less than two minutes should be done the moment it appears rather than filed away. Small deferrals pile into overwhelming clutter.",use:"Quick replies, tidying, and tiny admin the instant they show up.",avoid:"Do not let an endless drip of two-minute tasks shatter your deep, focused work.",act:"For the next hour, finish every sub-two-minute task on sight instead of deferring it."},
{n:5,t:"Murphy's Law",sub:"Anything that can go wrong, will",d:"If something has a way to fail, given enough time it eventually does. Not fate, but a reminder that plans and systems need slack and safeguards.",use:"When designing plans, build in buffers, backups, and contingencies at the failure points.",avoid:"Do not spiral into pessimism or paralysis. It is a prompt to prepare, not to fear everything.",act:"Pick one important plan. Name its most likely failure point and add one safeguard."},
{n:6,t:"Hofstadter's Law",sub:"It always takes longer than you expect",d:"'It always takes longer than you expect, even when you account for Hofstadter's Law.' We underestimate time chronically, even after correcting for it.",use:"When estimating, add a generous buffer, then add more. Assume unknowns you cannot yet see.",avoid:"Do not use it as an excuse for endless slippage. Buffer, but still commit to a date.",act:"Take your next estimate and multiply it by 1.5. Plan around that number."},
{n:7,t:"Hanlon's Razor",sub:"Do not assume malice where a mistake explains it",d:"Most harm from others is not a plot against you. Carelessness, haste, and simple error explain far more of the world than deliberate cruelty.",use:"When someone wrongs you, first assume a mistake, not an attack. It lowers stress and cools reactions.",avoid:"Do not use it to excuse repeated, clearly intentional harm. Patterns still matter.",act:"Recall one thing you took personally. Reframe it as a likely mistake and feel the shift."},
{n:8,t:"Occam's Razor",sub:"The simplest explanation is usually right",d:"Faced with competing explanations, the one requiring the fewest assumptions is usually correct. Do not invent complexity where none is needed.",use:"Debugging problems, diagnosing conflicts, and deciding with limited information.",avoid:"Simplest is not always true. Do not flatten a genuinely complex situation.",act:"Take one problem worrying you. Write the simplest explanation and test that first."},
{n:9,t:"The Dunning-Kruger Effect",sub:"The less you know, the more sure you feel",d:"Beginners often overrate their competence because they lack the knowledge to see their own gaps. True experts, seeing the depth, tend to underrate themselves.",use:"As a humility check whenever you feel certain in an unfamiliar area.",avoid:"Do not weaponize it to dismiss others. You are just as prone to it yourself.",act:"In a field you are new to, ask one expert what you are probably getting wrong."},
{n:10,t:"The Peter Principle",sub:"People rise to their level of incompetence",d:"In hierarchies, people get promoted on current performance until they land in a role they are no longer good at, and then they stall there.",use:"When choosing roles or promotions, ask whether the new skills differ from the ones being rewarded.",avoid:"Do not brand every struggling manager incompetent. Training and support change the picture.",act:"For your next step up, list the new skills it demands and start building one now."},
{n:11,t:"The Law of Diminishing Returns",sub:"More effort eventually yields less",d:"Past a certain point, each extra unit of effort produces a smaller gain. The tenth hour rarely matches the first, and the polish rarely matches the draft.",use:"To recognize when good enough truly is enough and it is time to ship.",avoid:"Do not stop too early on things that genuinely compound, like skill and relationships.",act:"Find one task you are over-polishing. Decide the point of enough, then ship it."},
{n:12,t:"The Compound Effect",sub:"Small actions repeated create huge results",d:"Tiny, consistent choices compound over time into outsized outcomes, for better or worse. The power is in repetition, not intensity.",use:"Building habits. Focus on showing up daily rather than on dramatic one-off bursts.",avoid:"Do not expect visible results early. The curve stays flat long before it bends upward.",act:"Choose one 1 percent habit. Commit to it daily for 30 days, however small."},
{n:13,t:"The Sunk Cost Fallacy",sub:"Do not throw good resources after bad",d:"We cling to failing efforts because of what we have already invested. Past costs are gone. Only future value should guide the decision ahead.",use:"When deciding whether to continue anything, weigh the future, not the spent past.",avoid:"Do not use it to quit at the first difficulty. Tell a dead end apart from a hard middle.",act:"Name one thing you continue only because you already invested in it. Reassess honestly."},
{n:14,t:"The Law of the Instrument",sub:"To a hammer, everything looks like a nail",d:"Over-rely on one familiar tool or method and you start forcing it onto every problem, even the ones it does not fit.",use:"When facing a new problem, deliberately ask what tool fits, not what tool you already know.",avoid:"Do not abandon a genuinely strong core skill just to appear versatile.",act:"Take a current problem. List two approaches from outside your usual toolkit."}
  ];

  function applyPower() {
    if (typeof LAWS === 'undefined') return;
    LAWS.length = 0;
    for (var i = 0; i < POWER.length; i++) LAWS.push(POWER[i]);
    if (typeof renderLaws === 'function') renderLaws();
    var sub = document.querySelector('#sec-laws .section-sub');
    if (sub) sub.textContent = 'All 48 laws: when to use, when to avoid';
  }

  function lawCard(l, useLabel, avoidLabel) {
    return '<div class="lc"><div class="lc-num">' + l.n + '</div><div><div class="lc-title">' + l.t + '</div><div class="lc-sub">' + l.sub + '</div><div class="lc-desc">' + l.d + '</div><div class="lc-when"><div class="lc-box use"><div class="lc-box-label">' + useLabel + '</div>' + l.use + '</div><div class="lc-box avoid"><div class="lc-box-label">' + avoidLabel + '</div>' + l.avoid + '</div></div><div class="lc-action"><div class="lc-action-label">Action Step</div>' + l.act + '</div></div></div>';
  }

  function renderLife() {
    var box = document.getElementById('life-box');
    if (!box) return;
    box.innerHTML = LIFE.map(function (l) { return lawCard(l, 'In Practice', 'Watch For'); }).join('');
  }

  function showLife() {
    document.getElementById('hero').style.display = 'none';
    var sections = document.querySelectorAll('.section');
    for (var i = 0; i < sections.length; i++) sections[i].classList.remove('active');
    document.getElementById('sec-life').classList.add('active');
    if (typeof setNav === 'function') setNav('life');
    renderLife();
    window.scrollTo({ top: 0 });
  }

  function injectLife() {
    if (document.getElementById('sec-life')) return;
    var section = document.createElement('div');
    section.className = 'section';
    section.id = 'sec-life';
    section.innerHTML = '<div class="section-top"><button class="back-btn" id="back-life">Back</button><div class="section-title">Life Laws</div><div class="section-sub">Mental models and principles for work and life</div></div><div id="life-box"></div>';
    document.getElementById('bottom-nav').insertAdjacentElement('beforebegin', section);

    var nav = document.createElement('button');
    nav.className = 'bnav-btn';
    nav.setAttribute('data-nav', 'life');
    nav.innerHTML = '<span class="bnav-icon"></span>Life';
    var settings = document.querySelector('[data-nav="settings"]');
    settings.parentNode.insertBefore(nav, settings);
    nav.addEventListener('click', showLife);
    document.getElementById('back-life').addEventListener('click', showHero);
    renderLife();
  }

  var ICONS = {
    home: '<path d="M3 10.5 12 4l9 6.5"/><path d="M5 9.5V20h14V9.5"/>',
    quotes: '<path d="M8 6C5.8 6 4 7.8 4 10s1.8 4 4 4c0 2-1.4 3.4-3 4"/><path d="M18 6c-2.2 0-4 1.8-4 4s1.8 4 4 4c0 2-1.4 3.4-3 4"/>',
    essays: '<path d="M12 6C10 4.6 6.6 4.6 4 5.2V18c2.6-.6 6-.6 8 1 2-1.6 5.4-1.6 8-1V5.2C17.4 4.6 14 4.6 12 6z"/><path d="M12 6v13"/>',
    laws: '<path d="M13 3 4 14h6l-1 7 9-11h-6z"/>',
    life: '<circle cx="12" cy="12" r="9"/><path d="m15.6 8.4-2.1 5.1-5.1 2.1 2.1-5.1z"/>',
    bookmarks: '<path d="M6 4h12v16l-6-4-6 4z"/>',
    settings: '<path d="M4 7h9"/><path d="M17 7h3"/><circle cx="15" cy="7" r="2"/><path d="M4 17h3"/><path d="M11 17h9"/><circle cx="9" cy="17" r="2"/>'
  };
  var LABELS = { home:'Today', quotes:'Quotes', essays:'Essays', laws:'Power', life:'Life', bookmarks:'Saved', settings:'Settings' };

  function svg(paths) {
    return '<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + paths + '</svg>';
  }

  function polishNav() {
    var style = document.createElement('style');
    style.textContent = '.bottom-nav{overflow:visible;justify-content:space-between;gap:0;padding:8px 6px max(8px,env(safe-area-inset-bottom))}.bottom-nav::-webkit-scrollbar{display:none}.bnav-btn{flex:1 1 0;min-width:0;padding:6px 2px;gap:5px}.bnav-btn .bnav-icon{font-size:0;line-height:0;display:flex;align-items:center;justify-content:center}.bnav-btn .bnav-icon svg{display:block}.bnav-btn{font-size:0.58rem;letter-spacing:0.02em;text-transform:none;font-weight:600;color:var(--ink-light)}.bnav-btn.active{color:var(--accent)}.bnav-btn svg{transition:transform .18s cubic-bezier(.25,1,.5,1)}.bnav-btn.active svg{transform:translateY(-1px) scale(1.04)}@media(min-width:768px){.bottom-nav{max-width:600px;gap:4px}}';
    document.head.appendChild(style);

    var buttons = document.querySelectorAll('.bnav-btn');
    for (var i = 0; i < buttons.length; i++) {
      var nav = buttons[i].getAttribute('data-nav');
      if (!ICONS[nav]) continue;
      buttons[i].innerHTML = '<span class="bnav-icon">' + svg(ICONS[nav]) + '</span>' + (LABELS[nav] || '');
    }
  }

  function setup() {
    applyPower();
    injectLife();
    if (typeof requestAnimationFrame === 'function') requestAnimationFrame(polishNav);
    else setTimeout(polishNav, 30);
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', setup);
  else setup();
})();
